### ISSUE TITLE
food price 기준 확인 필요

### ISSUE THREAD

**Issue by soyoon247** [human-calculator/travel_calculator#4]
food/models.py 에서 SOUTH_KOREA_FOOD_PRICE = 1089897.13 로 넣어놨는데 
update_food 스크립트에 넣어둔 값과 기준이 다른 것 같아서 확인이 필요합니다. 
근데 어차피 비율이 중요한 거니까 이 값을 바꾸면 될 것 같아요.

+ 1089897.13 이 값은 (western food types 한달 식비 + Asian food types 한달 식비) 로 나온 값이었는데 지금 해보니까 1337457.59 가 나오네요. 이것도 설마 실시간으로 아니면 매일 .. 달라지는 걸까? 하는 아찔함....  그치만 식품 물가 비율이 그렇게 급변하지 않겠지... 일단 고정값으로 넣어두자... 는 생각..

<img width="650" alt="image" src="https://user-images.githubusercontent.com/78311649/176800906-81c1cf29-6260-4212-838f-11937844ea1e.png">
지난달에 작성한 시트였는데 물가 오른 걸 여기서 체감하고 갑니다 ^^ (아닌가 이렇게 물가 오른 걸 보면 비율이 급변할 수 있나? + 아냐.. 전 세계적으로 올랐겠지.. 라는 생각까지)

**Comment by KYUNGJU-SHIM** [comment]
아하! SOUTH_KOREA_FOOD_PRICE 이 한 달 기준으로 들어간거였군요

food_model 에 입력한 값은 <한 끼 기준> 이었는데요, 
SOUTH_KOREA_FOOD_PRICE 도 한 끼 식사 기준으로 하는건 어떨까요?
우선은 그 기준으로 고쳐볼게요, 첨언해주세요!

+ 
헐 별개로 서울 식비도 지지난주 9,000 원 이었는데 지금 9,247 원....  물가 무슨일...
식비 정보도 주기적으로 업데이트 되나봐요, 우선 백로그에 식비도 주기적으로 스크래핑하여 수집하는 방식으로 변환하는 것 추가해둘게요!

**Comment by KYUNGJU-SHIM** [comment]
하루 기준으로 변경
